version: '3.4'

services:
  productsdb:
    container_name: productsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:9000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  

  products.api:
    container_name: products.api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - productsdb
    ports:
      - "8002:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"


