version: '3.4'

services:
  productsdb:
    image: mongo

  basketdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Services/Products/Products.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:

